### ISSUE TITLE
Merge sctb branch

### ISSUE THREAD

**Issue by josephholsten** [traditional-vi/meta#2]
https://github.com/traditional-vi/sctb-ex

notable changes:
* remove included libuxre
* remove included termcap

**Comment by sctb** [comment]
There's an important fix in `8ffba1c7`, but it should be rewritten to idiomatically use the `CP()` macro instead of `memmove(3)`.

**Comment by josephholsten** [comment]
closing, split into https://github.com/traditional-vi/meta/issues/7 https://github.com/traditional-vi/meta/issues/8 https://github.com/traditional-vi/meta/issues/9
